name: jongrhanrhao
services:
  postgres:
    image: postgres:16-alpine
    container_name: jongrhanrhao-db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - jongrhanrhao-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - jongrhanrhao-net
  backend:
    depends_on:
      - postgres
    image: tonnatthapon/jongrhanrhao-backend:latest
    container_name: jongrhanrhao-backend
    ports:
      - ${PORT}:3000
    networks:
      - jongrhanrhao-net
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
  frontend:
    depends_on:
      - backend
    image: tonnatthapon/jongrhanrhao-frontend:latest
    container_name: jongrhanrhao-frontend
    ports:
      - ${NGINX_PORT}:5173
    networks:
      - jongrhanrhao-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
volumes:
  JongRhanRhao-data:
networks:
  JongRhanRhao-net:
