name: jongrhanrhao
services:
  postgres:
    image: postgres:16-alpine
    container_name: jongrhanrhao-db
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - jongrhanrhao-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - jongrhanrhao-net
  backend:
    container_name: jongrhanrhao-backend
    build: ../JongRhanRhao-backend/.
    # image: tonnatthapon/jongrhanrhao-backend:latest
    ports:
      - ${SERVER_PORT}:4444
    environment:
      - NODE_ENV=${NODE_ENV}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_URL=${SERVER_URL}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
    depends_on:
      - postgres
    networks:
      - jongrhanrhao-net
  frontend:
    container_name: jongrhanrhao-frontend
    build: ../JongRhanRhao-frontend/.
    # image: tonnatthapon/jongrhanrhao-frontend:latest
    ports:
      - ${NGINX_PORT}:5555
    networks:
      - jongrhanrhao-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
    depends_on:
      - backend
networks:
  jongrhanrhao-net:
volumes:
  jongrhanrhao-data:
